ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-symlinks
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast
  - id: requirements-txt-fixer

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
