# Generated by Django 4.2.12 on 2024-09-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_activity_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
    ]
