# Generated by Django 5.1.1 on 2024-09-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_execution_executed_by_delete_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.activity",
            ),
        ),
    ]
