# Generated by Django 5.1.1 on 2024-09-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_execution_activity_alter_execution_executed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="date_created",
            field=models.DateField(
                default=datetime.date.today, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="execution_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="date done"
            ),
        ),
    ]
