# Generated by Django 5.1.1 on 2024-10-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_squashed_0009_alter_activity_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="notes",
            field=models.TextField(
                default="", verbose_name="Notes or description of the activity"
            ),
        ),
    ]
