# Generated by Django 5.1.1 on 2024-10-18 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_activity_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="executed_by_many",
            field=models.ManyToManyField(
                blank=True,
                related_name="which_people_did_it",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="executed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="who_did_it",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
