# Generated by Django 5.1.1 on 2024-10-18 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_auto_20241018_0631"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="execution",
            name="executed_by",
        ),
    ]
