# Generated by Django 5.1.1 on 2024-10-18 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_remove_execution_executed_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="execution",
            old_name="executed_by_many",
            new_name="executed_by",
        ),
    ]
