# Generated by Django 5.1.1 on 2024-10-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0016_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.dashboard",
            ),
        ),
    ]
