# Generated by Django 5.1.1 on 2024-10-22 13:06

from django.db import migrations


def create_default_dashboard(apps, schema_editor):
    Activity = apps.get_model("dashboard", "Activity")
    Dashboard = apps.get_model("dashboard", "Dashboard")
    dash = Dashboard.objects.create(slug="dashboard", name="Home maintenance")
    dash.save()

    for activity in Activity.objects.all():
        activity.dashboard = dash
        activity.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0017_activity_dashboard"),
    ]

    operations = [
        migrations.RunPython(create_default_dashboard),
    ]
