# Generated by Django 5.1.1 on 2024-10-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_auto_20241022_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.dashboard"
            ),
        ),
    ]
